In [32]:
import torch
import numpy as np

# How to create a tensor
#Method 1
x = torch.ones(2,2,2)
print(x)
print(x.dtype)    #Datatype
#Method 1.2 (Adding datatype qualification)
y = torch.rand(2,2,2, dtype=torch.float16) #Specify datatype while initializing the tensor
print(y)
print(y.dtype)
#Method 2 (From a list)
z = torch.tensor([1.5, 2.5, 3.0])
print(z)
#Method 3 (From a numpy array)
a = np.ones(2)
print(a)
b = torch.from_numpy(a) #can specify dtype here, as done previously
print(b)

# Torch tensor -> Numpy
z = z.numpy()
print(z)

#NOTE: if a torch tensor is converted to a numpy array, or vice versa, AND they exist on the same processor (CPU or GPU),
#they would be sharing the same memory space and modifying one would modify the value in other as well.

#Size of tensor
print(x.size())

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.float32
tensor([[[0.8110, 0.3755],
         [0.1348, 0.2217]],

        [[0.8926, 0.4082],
         [0.1201, 0.1543]]], dtype=torch.float16)
torch.float16
tensor([1.5000, 2.5000, 3.0000])
[1. 1.]
tensor([1., 1.], dtype=torch.float64)
[1.5 2.5 3. ]
torch.Size([2, 2, 2])


In [19]:
# Operations on Tensors

#Addition
z = x + y
print(z)
z = torch.add(x,y)
print(z)

#In-Place addition
t = y
t = x + t
print(t)
t.add_(x) #Using inbuild fxn. All fxn with a trailing _ in the name mean that the fxn performs an in-place operation (on the same var)
print(t)

#Subtraction
z = x - y
print(z)
z = torch.sub(x,y)
print(z)

#In-Place subtraction
t = y
t = x - t
print(t)
t.sub_(x) #Using inbuild fxn. All fxn with a trailing _ in the name mean that the fxn performs an in-place operation (on the same var)
print(t)


#Multiplication
# Use * and mul
#Division
# Use / and div

tensor([[[1.9966, 1.6294],
         [1.5669, 1.7505]],

        [[1.6104, 1.0918],
         [1.7817, 1.9980]]])
tensor([[[1.9966, 1.6294],
         [1.5669, 1.7505]],

        [[1.6104, 1.0918],
         [1.7817, 1.9980]]])
tensor([[[1.9966, 1.6294],
         [1.5669, 1.7505]],

        [[1.6104, 1.0918],
         [1.7817, 1.9980]]])
tensor([[[2.9966, 2.6294],
         [2.5669, 2.7505]],

        [[2.6104, 2.0918],
         [2.7817, 2.9980]]])
tensor([[[0.0034, 0.3706],
         [0.4331, 0.2495]],

        [[0.3896, 0.9082],
         [0.2183, 0.0020]]])
tensor([[[0.0034, 0.3706],
         [0.4331, 0.2495]],

        [[0.3896, 0.9082],
         [0.2183, 0.0020]]])
tensor([[[0.0034, 0.3706],
         [0.4331, 0.2495]],

        [[0.3896, 0.9082],
         [0.2183, 0.0020]]])
tensor([[[-0.9966, -0.6294],
         [-0.5669, -0.7505]],

        [[-0.6104, -0.0918],
         [-0.7817, -0.9980]]])


In [25]:
# Slicing a tensor (Taking out a particular row or column, or range thereof)
x = torch.rand(5,3)
print(x)
print(x[:,2])
print(x[1,:])
print(x[1,1].item()) #Gets the actual value of the tensor element

# Reshaping a tensor
x = torch.rand(4,4)
y = x.view(16) #Number of elements must remain same (4*4)
print(y)
y = x.view(2,8)
print(y)
print(x.view(-1,8)) #-1 means pytorch should get this value based on the other params

tensor([[0.3401, 0.0841, 0.6951],
        [0.2099, 0.3620, 0.0337],
        [0.2394, 0.2931, 0.0833],
        [0.1366, 0.1106, 0.3499],
        [0.6755, 0.3895, 0.0974]])
tensor([0.6951, 0.0337, 0.0833, 0.3499, 0.0974])
tensor([0.2099, 0.3620, 0.0337])
0.3619650602340698
tensor([0.6768, 0.9084, 0.8926, 0.0063, 0.3548, 0.0606, 0.2891, 0.9227, 0.2373,
        0.0882, 0.1863, 0.0218, 0.2893, 0.1641, 0.0835, 0.8412])
tensor([[0.6768, 0.9084, 0.8926, 0.0063, 0.3548, 0.0606, 0.2891, 0.9227],
        [0.2373, 0.0882, 0.1863, 0.0218, 0.2893, 0.1641, 0.0835, 0.8412]])
tensor([[0.6768, 0.9084, 0.8926, 0.0063, 0.3548, 0.0606, 0.2891, 0.9227],
        [0.2373, 0.0882, 0.1863, 0.0218, 0.2893, 0.1641, 0.0835, 0.8412]])
